export const HOST_URL = "http://127.0.0.1:5000";
const prefix = "/";
export const login = `${prefix}login/`;
export const server = `${prefix}client/testservice`;
export const history = `${prefix}history`;
export const average = `${prefix}average`;
export const endpos = `${prefix}dealer/endpos`;
export const realized = `${prefix}dealer/realized_pl`;
export const effective = `${prefix}dealer/effective_pl`;
